USE SUPERMERCADO_JPV_V6;
GO

-- =============================================
-- 1. ANALISIS DE DESEMPENO: VENDEDORES
-- =============================================

-- A. Ranking de Vendedores por Rentabilidad Real
SELECT 
    VD.VENDEDOR,
    COUNT(DISTINCT V.ID_VENTA) AS Total_Transacciones,
    FORMAT(SUM(DV.SUBTOTAL), 'N2') AS Facturacion_Neta,
    FORMAT(SUM(DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA)), 'N2') AS Ganancia_Real,
    RANK() OVER (ORDER BY SUM(DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA)) DESC) AS Ranking_Rentabilidad
FROM VENDEDOR VD
INNER JOIN VENTAS V ON VD.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN DETALLE_VENTAS DV ON V.ID_VENTA = DV.ID_VENTA
INNER JOIN PRODUCTO PR ON DV.ID_PRODUCTO = PR.ID_PRODUCTO
WHERE V.ESTADO = 'COMPLETADA'
GROUP BY VD.VENDEDOR;

-- B. Vendedores Inactivos
SELECT VENDEDOR, SUCURSAL, fecha_creacion AS Fecha_Ingreso
FROM VENDEDOR
WHERE ID_VENDEDOR NOT IN (SELECT DISTINCT ID_VENDEDOR FROM VENTAS);

-- =============================================
-- 2. ANALISIS DE PRODUCTOS (EFICIENCIA Y STOCK)
-- =============================================

-- A. Productos con mayor Tasa de Devolucion
SELECT 
    P.PRODUCTO,
    Stats.Vendidas AS Unidades_Vendidas,
    Stats.Devueltas AS Unidades_Devueltas,
    CAST(Stats.Devueltas * 100.0 / NULLIF(Stats.Vendidas, 0) AS DECIMAL(5,2)) AS Porcentaje_Retorno
FROM PRODUCTO P
CROSS APPLY (
    SELECT 
        ISNULL(SUM(DV.CANTIDAD), 0) AS Vendidas,
        ISNULL((SELECT SUM(DNC.CANTIDAD_DEVUELTA) FROM DETALLE_NOTA_CREDITO DNC WHERE DNC.ID_PRODUCTO = P.ID_PRODUCTO), 0) AS Devueltas
    FROM DETALLE_VENTAS DV WHERE DV.ID_PRODUCTO = P.ID_PRODUCTO
) AS Stats
WHERE Stats.Vendidas > 0
ORDER BY Porcentaje_Retorno DESC;

-- B. Productos Mas Rentables
SELECT 
    P.PRODUCTO,
    Calc.Unidades AS Unidades_Vendidas,
    FORMAT(Calc.Total_Vendido - (Calc.Unidades * P.PRECIO_COMPRA), 'N2') AS Margen_Ganancia_Acumulado
FROM PRODUCTO P
CROSS APPLY (
    SELECT 
        ISNULL(SUM(DV.CANTIDAD), 0) AS Unidades,
        ISNULL(SUM(DV.SUBTOTAL), 0) AS Total_Vendido
    FROM DETALLE_VENTAS DV 
    WHERE DV.ID_PRODUCTO = P.ID_PRODUCTO
) AS Calc
WHERE Calc.Unidades > 0
ORDER BY (Calc.Total_Vendido - (Calc.Unidades * P.PRECIO_COMPRA)) DESC;

-- C. Productos Muertos (Sin ventas)
SELECT PRODUCTO, STOCK, PRECIO_VENTA
FROM PRODUCTO
WHERE ID_PRODUCTO NOT IN (SELECT DISTINCT ID_PRODUCTO FROM DETALLE_VENTAS);

-- =============================================
-- 3. INTELIGENCIA DE CLIENTES (FIDELIZACION)
-- =============================================

-- A. Clientes VIP (Mas rentables)
SELECT TOP 10
    C.NOMBRE_CLIENTE + ' ' + C.APELLIDO_CLIENTE AS Cliente,
    COUNT(DISTINCT V.ID_VENTA) AS Cantidad_Ordenes,
    FORMAT(SUM(V.TOTAL_VENTA), 'N2') AS Facturacion_Bruta,
    FORMAT(SUM(DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA)), 'N2') AS Margen_Neto_Dejado
FROM CLIENTE C
INNER JOIN VENTAS V ON C.ID_CLIENTE = V.ID_CLIENTE
INNER JOIN DETALLE_VENTAS DV ON V.ID_VENTA = DV.ID_VENTA
INNER JOIN PRODUCTO PR ON DV.ID_PRODUCTO = PR.ID_PRODUCTO
WHERE V.ESTADO = 'COMPLETADA'
GROUP BY C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE
ORDER BY SUM(DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA)) DESC;

-- =============================================
-- 4. GEOMARKETING: RANKING POR PROVINCIA
-- =============================================
SELECT 
    P.nombreProvincia AS Provincia,
    COUNT(DISTINCT V.ID_VENTA) AS Cantidad_Ventas,
    FORMAT(SUM(V.TOTAL_VENTA), 'N2') AS Volumen_Dinero,
    RANK() OVER (ORDER BY SUM(V.TOTAL_VENTA) DESC) AS Ranking_Mercado
FROM PROVINCIAS P
INNER JOIN VENDEDOR VD ON P.id_provincia = VD.PROVINCIA
INNER JOIN VENTAS V ON VD.ID_VENDEDOR = V.ID_VENDEDOR
GROUP BY P.nombreProvincia;
GO

-- =============================================
-- 5. ANALISIS PIVOTE: VENTAS POR TIEMPO, VENDEDOR Y PRODUCTO
-- =============================================

-- A. Ventas Mensuales por Ano (Pivote con Totales)
-- Muestra el flujo de dinero por mes y ano, con sumatoria final
SELECT 
    ISNULL(CAST(MONTH(FECHA) AS VARCHAR), 'TOTAL') AS Mes,
    FORMAT(SUM(CASE WHEN YEAR(FECHA) = 2023 THEN TOTAL_VENTA ELSE 0 END), 'N2') AS [2023],
    FORMAT(SUM(CASE WHEN YEAR(FECHA) = 2024 THEN TOTAL_VENTA ELSE 0 END), 'N2') AS [2024],
    FORMAT(SUM(CASE WHEN YEAR(FECHA) = 2025 THEN TOTAL_VENTA ELSE 0 END), 'N2') AS [2025],
    FORMAT(SUM(TOTAL_VENTA), 'N2') AS TOTAL_FILA
FROM VENTAS
WHERE ESTADO = 'COMPLETADA'
GROUP BY ROLLUP(MONTH(FECHA))
ORDER BY CASE WHEN MONTH(FECHA) IS NULL THEN 13 ELSE MONTH(FECHA) END;

-- B. Ventas por Vendedor y Ano (Pivote)
-- Comportamiento anual de cada vendedor con gran total a la derecha y abajo
SELECT 
    ISNULL(VD.VENDEDOR, 'TOTAL GENERAL') AS Vendedor,
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2023 THEN V.TOTAL_VENTA ELSE 0 END), 'N2') AS [2023],
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2024 THEN V.TOTAL_VENTA ELSE 0 END), 'N2') AS [2024],
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2025 THEN V.TOTAL_VENTA ELSE 0 END), 'N2') AS [2025],
    FORMAT(SUM(V.TOTAL_VENTA), 'N2') AS TOTAL_VENTAS
FROM VENTAS V
INNER JOIN VENDEDOR VD ON V.ID_VENDEDOR = VD.ID_VENDEDOR
WHERE V.ESTADO = 'COMPLETADA'
GROUP BY ROLLUP(VD.VENDEDOR);

-- C. Ventas por Producto (Anual y Mensual) con Totales
-- Ranking de productos distribuido por anos y meses
SELECT 
    ISNULL(PR.PRODUCTO, 'TOTAL CATEGORIA') AS Producto,
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2023 THEN DV.SUBTOTAL ELSE 0 END), 'N2') AS [Ventas_2023],
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2024 THEN DV.SUBTOTAL ELSE 0 END), 'N2') AS [Ventas_2024],
    FORMAT(SUM(CASE WHEN YEAR(V.FECHA) = 2025 THEN DV.SUBTOTAL ELSE 0 END), 'N2') AS [Ventas_2025],
    FORMAT(SUM(DV.SUBTOTAL), 'N2') AS TOTAL_HISTORICO
FROM DETALLE_VENTAS DV
INNER JOIN VENTAS V ON DV.ID_VENTA = V.ID_VENTA
INNER JOIN PRODUCTO PR ON DV.ID_PRODUCTO = PR.ID_PRODUCTO
WHERE V.ESTADO = 'COMPLETADA'
GROUP BY ROLLUP(PR.PRODUCTO);



select * from CLIENTE

