USE SUPERMERCADO_JPV_V6;
GO

-- =============================================
-- 1. MODULO DE LOGISTICA Y ENTREGAS
-- =============================================

-- Catalogo de estados de entrega
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ESTADO_ENTREGA')
BEGIN
    CREATE TABLE ESTADO_ENTREGA (
        ID_ESTADO INT PRIMARY KEY,
        DESCRIPCION VARCHAR(50) NOT NULL
    );

    INSERT INTO ESTADO_ENTREGA VALUES 
    (1, 'Pendiente de Empaque'), 
    (2, 'En Ruta / Delivery'), 
    (3, 'Entregado'), 
    (4, 'Cancelado / No Recibido');
END

-- Historial de seguimiento por factura
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SEGUIMIENTO_ENTREGA')
BEGIN
    CREATE TABLE SEGUIMIENTO_ENTREGA (
        ID_SEGUIMIENTO INT PRIMARY KEY IDENTITY(1,1),
        ID_VENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(ID_VENTA),
        ID_ESTADO INT NOT NULL FOREIGN KEY REFERENCES ESTADO_ENTREGA(ID_ESTADO),
        COMENTARIO VARCHAR(255),
        UBICACION_ACTUAL VARCHAR(100),
        FECHA_ACTUALIZACION DATETIME DEFAULT GETDATE(),
        ACTUALIZADO_POR VARCHAR(50)
    );
END
GO

-- =============================================
-- 2. MODULO DE NOTAS DE CREDITO (DEVOLUCIONES)
-- =============================================

IF NOT EXISTS (SELECT 1 FROM TIPO_NCF WHERE SERIE_NCF = 'E34')
    INSERT INTO TIPO_NCF (ID_TIPO_NCF, CODIGO_INTERNO, SERIE_NCF, DESCRIPCION, REQUIERE_RNC)
    VALUES (5, '34', 'E34', 'Nota de Credito Electronica (Devolucion)', 1);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NOTA_CREDITO')
BEGIN
    CREATE TABLE NOTA_CREDITO (
        ID_NOTA INT PRIMARY KEY IDENTITY(1,1),
        ID_VENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(ID_VENTA),
        NCF_NOTA_CREDITO VARCHAR(19) NOT NULL,
        NCF_FACTURA_ORIGINAL VARCHAR(19) NOT NULL,
        FECHA DATETIME DEFAULT GETDATE(),
        MOTIVO VARCHAR(200),
        TIPO_DEVOLUCION VARCHAR(20),
        TOTAL_DEVUELTO DECIMAL(12,2) NOT NULL,
        ITBIS_DEVUELTO DECIMAL(12,2) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DETALLE_NOTA_CREDITO')
BEGIN
    CREATE TABLE DETALLE_NOTA_CREDITO (
        ID_DETALLE_NOTA INT PRIMARY KEY IDENTITY(1,1),
        ID_NOTA INT FOREIGN KEY REFERENCES NOTA_CREDITO(ID_NOTA),
        ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
        CANTIDAD_DEVUELTA INT NOT NULL,
        PRECIO_UNITARIO_REF DECIMAL(9,2) NOT NULL
    );
END
GO

-- =============================================
-- 3. MODULO DE CAJA (INGRESOS Y EGRESOS)
-- =============================================

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MOVIMIENTOS_CAJA')
BEGIN
    CREATE TABLE MOVIMIENTOS_CAJA (
        ID_MOVIMIENTO INT PRIMARY KEY IDENTITY(1,1),
        FECHA DATETIME DEFAULT GETDATE(),
        TIPO_MOVIMIENTO VARCHAR(10),
        CATEGORIA VARCHAR(50),
        DESCRIPCION VARCHAR(200),
        MONTO DECIMAL(12,2) NOT NULL,
        ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO),
        ESTADO VARCHAR(15) DEFAULT 'ACTIVO'
    );
END
GO

-- =============================================
-- 4. LOGICA AUTOMATICA: TRIGGER RETORNO STOCK
-- =============================================

CREATE OR ALTER TRIGGER TRG_RETORNO_STOCK_POR_DEVOLUCION
ON DETALLE_NOTA_CREDITO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE P
    SET P.STOCK = P.STOCK + I.CANTIDAD_DEVUELTA
    FROM PRODUCTO P
    INNER JOIN inserted I ON P.ID_PRODUCTO = I.ID_PRODUCTO;
END
GO

-- =============================================
-- 5. PROCEDIMIENTOS ALMACENADOS DE GESTION
-- =============================================

CREATE OR ALTER PROCEDURE SP_GENERAR_NOTA_CREDITO
    @ID_Venta INT,
    @Motivo VARCHAR(200),
    @EsTotal BIT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DECLARE @NCF_Original VARCHAR(19), @TotalFactura DECIMAL(12,2), @ITBISFactura DECIMAL(12,2);
        SELECT @NCF_Original = NCF_GENERADO, @TotalFactura = TOTAL_VENTA, @ITBISFactura = TOTAL_ITBIS 
        FROM VENTAS WHERE ID_VENTA = @ID_Venta;
        DECLARE @NCF_Nota VARCHAR(19) = 'E34' + RIGHT('0000000000' + CAST(ABS(CHECKSUM(NEWID())) % 10000000 AS VARCHAR), 10);
        INSERT INTO NOTA_CREDITO (ID_VENTA, NCF_NOTA_CREDITO, NCF_FACTURA_ORIGINAL, MOTIVO, TIPO_DEVOLUCION, TOTAL_DEVUELTO, ITBIS_DEVUELTO)
        VALUES (@ID_Venta, @NCF_Nota, @NCF_Original, @Motivo, CASE WHEN @EsTotal = 1 THEN 'TOTAL' ELSE 'PARCIAL' END, @TotalFactura, @ITBISFactura);
        DECLARE @ID_Nota INT = SCOPE_IDENTITY();
        IF @EsTotal = 1
        BEGIN
            INSERT INTO DETALLE_NOTA_CREDITO (ID_NOTA, ID_PRODUCTO, CANTIDAD_DEVUELTA, PRECIO_UNITARIO_REF)
            SELECT @ID_Nota, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO FROM DETALLE_VENTAS WHERE ID_VENTA = @ID_Venta;
            UPDATE VENTAS SET ESTADO = 'ANULADA' WHERE ID_VENTA = @ID_Venta;
        END
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE SP_REGISTRAR_MOVIMIENTO_CAJA
    @Tipo VARCHAR(10),
    @Categoria VARCHAR(50),
    @Monto DECIMAL(12,2),
    @Desc VARCHAR(200),
    @Usuario INT
AS
BEGIN
    INSERT INTO MOVIMIENTOS_CAJA (TIPO_MOVIMIENTO, CATEGORIA, MONTO, DESCRIPCION, ID_USUARIO)
    VALUES (@Tipo, @Categoria, @Monto, @Desc, @Usuario);
END
GO

-- =============================================
-- 6. VISTAS DE CONSULTA (REPORTE FINANCIERO)
-- =============================================

CREATE OR ALTER VIEW VISTA_FLUJO_CAJA_CONSOLIDADO AS
SELECT 'Venta Pos' AS Origen, FECHA, 'INGRESO' AS Tipo, TOTAL_VENTA AS Monto FROM VENTAS WHERE ESTADO = 'COMPLETADA'
UNION ALL
SELECT 'Nota Credito' AS Origen, FECHA, 'EGRESO' AS Tipo, TOTAL_DEVUELTO * -1 AS Monto FROM NOTA_CREDITO
UNION ALL
SELECT CATEGORIA, FECHA, TIPO_MOVIMIENTO, CASE WHEN TIPO_MOVIMIENTO = 'EGRESO' THEN MONTO * -1 ELSE MONTO END FROM MOVIMIENTOS_CAJA;
GO

CREATE OR ALTER VIEW VISTA_ALERTA_STOCK AS
SELECT ID_PRODUCTO, PRODUCTO, STOCK, 
       CASE WHEN STOCK <= 5 THEN 'CRITICO' WHEN STOCK <= 15 THEN 'BAJO' ELSE 'OK' END AS Estatus
FROM PRODUCTO;
GO
