import pyodbc

server = r'(localdb)\MSSQLLocalDB'
conn_str = f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE=SUPERMERCADO_JPV_V6;Trusted_Connection=yes;'

sql_alter_tables = [
    # Agregar columnas faltantes detectadas en el error
    "IF COL_LENGTH('TIPO_NCF', 'CODIGO_INTERNO') IS NULL ALTER TABLE TIPO_NCF ADD CODIGO_INTERNO VARCHAR(10) DEFAULT '00'",
    "IF COL_LENGTH('METODO_ENTREGA', 'ES_ONLINE') IS NULL ALTER TABLE METODO_ENTREGA ADD ES_ONLINE BIT DEFAULT 0",
    "IF COL_LENGTH('PROVINCIAS', 'latitud') IS NULL ALTER TABLE PROVINCIAS ADD latitud DECIMAL(9,6) DEFAULT 0",
    "IF COL_LENGTH('PROVINCIAS', 'longitud') IS NULL ALTER TABLE PROVINCIAS ADD longitud DECIMAL(9,6) DEFAULT 0"
]

sql_view = """
CREATE OR ALTER VIEW VISTA_ANALITICA_DETALLADA AS
SELECT 
    V.ID_VENTA AS ID_PEDIDO,
    DV.ID_DETALLE,
    V.FECHA,
    YEAR(V.FECHA) AS Anio,
    MONTH(V.FECHA) AS Mes,
    DATENAME(MONTH, V.FECHA) AS Nombre_Mes,
    V.ID_CLIENTE,
    CONCAT(C.NOMBRE_CLIENTE, ' ', C.APELLIDO_CLIENTE) AS Cliente,
    C.RNC_CEDULA,
    C.TIPO_PERSONA,
    TN.CODIGO_INTERNO,
    TN.SERIE_NCF,
    TN.DESCRIPCION AS Tipo_Comprobante,
    V.NCF_GENERADO,
    CP.NOMBRE_CONDICION AS Condicion_Pago,
    CASE WHEN CP.ES_CREDITO = 1 THEN 'Crédito' ELSE 'Contado' END AS Tipo_Venta_Financiera,
    MP.METODO AS Metodo_Pago,
    ME.TIPO_ENTREGA,
    CASE WHEN ME.ES_ONLINE = 1 THEN 'Online' ELSE 'Física' END AS Canal_Venta,
    V.ID_VENDEDOR,
    VD.VENDEDOR AS Nombre_Vendedor,
    G.Genero AS Genero_Vendedor,
    VD.SUCURSAL,
    P.nombreProvincia AS Provincia_Vendedor,
    R.REGION AS Region_Vendedor,
    P.latitud,
    P.longitud,
    DV.ID_PRODUCTO,
    PR.PRODUCTO AS Nombre_Producto,
    DV.CANTIDAD,
    CAST(DV.PRECIO_UNITARIO AS DECIMAL(18,2)) AS PRECIO_VENTA_UNITARIO,
    CAST(PR.PRECIO_COMPRA AS DECIMAL(18,2)) AS COSTO_UNITARIO,
    CAST(DV.ITBIS_UNITARIO AS DECIMAL(18,2)) AS ITBIS_UNITARIO,
    CAST(DV.SUBTOTAL AS DECIMAL(18,2)) AS VENTA_NETA, 
    CAST((DV.ITBIS_UNITARIO * DV.CANTIDAD) AS DECIMAL(18,2)) AS TOTAL_ITBIS, 
    CAST((DV.SUBTOTAL + (DV.ITBIS_UNITARIO * DV.CANTIDAD)) AS DECIMAL(18,2)) AS VENTA_BRUTA, 
    CAST(DV.CANTIDAD * PR.PRECIO_COMPRA AS DECIMAL(18,2)) AS COSTO_TOTAL,
    CAST(DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA) AS DECIMAL(18,2)) AS MARGEN_BENEFICIO,
    CAST(CASE WHEN DV.SUBTOTAL = 0 THEN 0 ELSE ((DV.SUBTOTAL - (DV.CANTIDAD * PR.PRECIO_COMPRA)) / NULLIF(DV.SUBTOTAL, 0)) * 100 END AS DECIMAL(7,2)) AS PORCENTAJE_MARGEN,
    RANK() OVER (PARTITION BY V.ID_CLIENTE ORDER BY DV.SUBTOTAL DESC) AS RANK_PRODUCTO_EN_HISTORIAL_CLIENTE,
    'N/A' AS foto_Productos_url,
    'N/A' AS foto_Vendedor_url
FROM VENTAS V
INNER JOIN DETALLE_VENTAS DV ON V.ID_VENTA = DV.ID_VENTA
INNER JOIN CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN VENDEDOR VD ON V.ID_VENDEDOR = VD.ID_VENDEDOR
LEFT JOIN Genero G ON VD.id_genero = G.ID_Genero
INNER JOIN PROVINCIAS P ON VD.PROVINCIA = P.id_provincia
INNER JOIN REGION R ON P.id_region = R.ID_REGION
INNER JOIN PRODUCTO PR ON DV.ID_PRODUCTO = PR.ID_PRODUCTO
INNER JOIN TIPO_NCF TN ON V.ID_TIPO_NCF = TN.ID_TIPO_NCF
INNER JOIN CONDICION_PAGO CP ON V.ID_CONDICION = CP.ID_CONDICION
INNER JOIN METODO_PAGO MP ON V.ID_METODO_PAGO = MP.ID_METODO
INNER JOIN METODO_ENTREGA ME ON V.ID_ENTREGA = ME.ID_ENTREGA;
"""

try:
    conn = pyodbc.connect(conn_str, autocommit=True)
    cursor = conn.cursor()
    
    # 1. Alterar tablas
    print("Reparando estructura de tablas...")
    for sql in sql_alter_tables:
        cursor.execute(sql)
        
    # 2. Crear Vendedor Dummy si no existe
    cursor.execute("IF NOT EXISTS (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR=1) INSERT INTO VENDEDOR (ID_VENDEDOR, VENDEDOR, id_genero, SUCURSAL, PROVINCIA) VALUES (1, 'Vendedor Base', 1, 'Central', 1)")
    cursor.execute("IF NOT EXISTS (SELECT * FROM Genero WHERE ID_Genero=1) INSERT INTO Genero VALUES (1, 'Masculino')")
    
    # 3. Crear la Vista
    print("Creando vista...")
    cursor.execute(sql_view)
    
    print("✅ Estructura reparada y Vista 'VISTA_ANALITICA_DETALLADA' creada.")
    
except Exception as e:
    print(f"❌ Error: {e}")